name: 'Vibe Clock'
description: 'Generate AI coding agent usage SVGs for your GitHub profile — WakaTime for AI agents'
author: 'dexhunter'
branding:
  icon: 'clock'
  color: 'blue'

inputs:
  gist_id:
    description: 'GitHub Gist ID containing vibe-clock-data.json'
    required: true
  theme:
    description: 'Theme: dark or light'
    required: false
    default: 'dark'
  output_dir:
    description: 'Directory to write SVG files'
    required: false
    default: './images'
  chart_types:
    description: 'Chart types to generate (comma-separated or "all")'
    required: false
    default: 'all'
  commit:
    description: 'Auto-commit generated SVGs'
    required: false
    default: 'true'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'chore: update vibe-clock stats'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install vibe-clock
      shell: bash
      run: pip install git+https://github.com/dexhunter/vibe-clock.git@${{ github.action_ref }}

    - name: Fetch stats from gist
      shell: bash
      env:
        GIST_ID: ${{ inputs.gist_id }}
        REPO_OWNER: ${{ github.repository_owner }}
      run: |
        curl -sf "https://gist.githubusercontent.com/${REPO_OWNER}/${GIST_ID}/raw/vibe-clock-data.json" \
          -o /tmp/vibe-clock-data.json

    - name: Generate SVGs
      shell: bash
      env:
        OUTPUT_DIR: ${{ inputs.output_dir }}
        CHART_TYPES: ${{ inputs.chart_types }}
        THEME: ${{ inputs.theme }}
      run: |
        mkdir -p "${OUTPUT_DIR}"
        vibe-clock render --from-json /tmp/vibe-clock-data.json \
          --type "${CHART_TYPES}" --theme "${THEME}" --output "${OUTPUT_DIR}"

    - name: Commit and push
      if: inputs.commit == 'true'
      shell: bash
      env:
        OUTPUT_DIR: ${{ inputs.output_dir }}
        COMMIT_MSG: ${{ inputs.commit_message }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${OUTPUT_DIR}"
        git diff --staged --quiet || git commit -m "${COMMIT_MSG}"
        git push
